import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const number = 3;
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className='title'>Home</h1>
      <style jsx>
        {`
        .title{
          display: ${number > 2 ? "block" : "none"}; {/*write js code inside css code !!!*/}
          color:blue;
        }
        `}

      </style>
    </div>
  )
}
